# Generated by Django 4.0.2 on 2022-04-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='virtual_domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Domínio virtual',
                'verbose_name_plural': 'Domínios virtuais',
                'db_table': 'virtual_domains',
            },
        ),
        migrations.CreateModel(
            name='virtual_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=106)),
                ('email', models.CharField(max_length=100)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.virtual_domains')),
            ],
            options={
                'verbose_name': 'Usuário virtual',
                'verbose_name_plural': 'Usuários virtuais',
                'db_table': 'virtual_users',
            },
        ),
        migrations.CreateModel(
            name='virtual_aliases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emails.virtual_domains')),
            ],
            options={
                'verbose_name': 'Atalho virtual',
                'verbose_name_plural': 'Atalhos virtuais',
                'db_table': 'virtual_aliases',
            },
        ),
    ]
