# Generated by Django 4.0.2 on 2022-04-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual_aliases',
            name='destination',
            field=models.CharField(db_column='destination', max_length=100),
        ),
        migrations.AlterField(
            model_name='virtual_aliases',
            name='domain_id',
            field=models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='emails.virtual_domains'),
        ),
        migrations.AlterField(
            model_name='virtual_aliases',
            name='source',
            field=models.CharField(db_column='source', max_length=100),
        ),
        migrations.AlterField(
            model_name='virtual_domains',
            name='name',
            field=models.CharField(db_column='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='virtual_users',
            name='domain_id',
            field=models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='emails.virtual_domains'),
        ),
        migrations.AlterField(
            model_name='virtual_users',
            name='email',
            field=models.CharField(db_column='email', max_length=100),
        ),
        migrations.AlterField(
            model_name='virtual_users',
            name='password',
            field=models.CharField(db_column='password', max_length=106),
        ),
    ]
