# Generated by Django 4.0.2 on 2022-04-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_virtual_aliases_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual_users',
            name='password',
            field=models.CharField(db_column='password', max_length=250),
        ),
    ]
