# Generated by Django 4.0.2 on 2022-02-24 17:42

from django.db import migrations, models
import django.db.models.deletion
import documentos.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200, verbose_name='Tipo de documento')),
            ],
        ),
        migrations.CreateModel(
            name='arquivosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('nome', models.CharField(default='Sem título', max_length=200, verbose_name='Nome do arquivo')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=documentos.models.local_renomear)),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade do documento')),
                ('tempoValidade', models.SmallIntegerField(blank=True, default=30, null=True, verbose_name='Tempo de validade')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tipoArquivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arquivos', to='documentos.tipoarquivo')),
            ],
        ),
    ]
