# Generated by Django 4.0.3 on 2022-03-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_arquivosmodel_tipoarquivo_delete_tipoarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosmodel',
            name='cliente_id',
            field=models.IntegerField(default=41),
        ),
        migrations.AlterField(
            model_name='arquivosmodel',
            name='tipoArquivo',
            field=models.CharField(choices=[('certidao', 'Certidão'), ('comprovante', 'Comprovante'), ('declaracao', 'Declaração'), ('docPessoal', 'Documentação pessoal'), ('requerimento', 'Requerimento')], max_length=20, verbose_name='Tipo de arquivo'),
        ),
    ]
