# Generated by Django 4.0.2 on 2022-03-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_arquivosmodel_cliente_id_and_more'),
        ('documentos', '0004_alter_arquivosmodel_tipoarquivo'),
    ]

    operations = [
    ]
