# Generated by Django 4.0.2 on 2022-05-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_merge_20220306_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosmodel',
            name='dataRegistro',
            field=models.DateTimeField(auto_now=True, verbose_name='Data do registro'),
        ),
    ]
