# Generated by Django 4.0.2 on 2022-05-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_arquivosmodel_dataregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivosmodel',
            name='formatoArquivo',
            field=models.CharField(blank=True, default='pdf', max_length=5, verbose_name='Nome do Arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivosmodel',
            name='nome',
            field=models.CharField(default='pdf', max_length=200, verbose_name='Nome do arquivo'),
        ),
    ]
