# Generated by Django 4.0.2 on 2022-05-27 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0017_remove_historicoconsultasprocessosmodel_consulta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=200, verbose_name='Identificação do processo')),
                ('protocolo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Protocolo')),
                ('sistemaVinculado', models.CharField(choices=[('SIGMA', 'SIGMA - EB'), ('SINARM', 'SINARM - PF'), ('OUTROS', 'Outros..')], max_length=10, verbose_name='Sistema vinculado')),
                ('descricao', models.TextField(verbose_name='Descrição da consulta')),
                ('consultaAtiva', models.BooleanField(default=True, verbose_name='Consulta Ativa')),
                ('dataVerificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da última verificação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='clientes.clientemodel')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['cliente', 'dataVerificacao'],
            },
        ),
        migrations.CreateModel(
            name='pendenciasModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Identificação da pendência')),
                ('textoPendencia', models.TextField(blank=True, null=True, verbose_name='Detalhamento da pendência')),
                ('statusPendencia', models.BooleanField(default=False, verbose_name='Realizado')),
                ('escalaPrioridade', models.SmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2, verbose_name='Escala de prioridade')),
                ('dataRegistro', models.DateTimeField(auto_now=True)),
                ('dataLimite', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite ou Vencimento')),
                ('dataConclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data da conclusão')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='clientes.clientemodel')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processosPendencias', to='processos.processosmodel')),
                ('usuario', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pendendias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendência',
                'verbose_name_plural': 'Pendências',
                'ordering': ['escalaPrioridade', 'dataRegistro'],
            },
        ),
        migrations.CreateModel(
            name='historicoProcessosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da consulta')),
                ('textoConsulta', models.TextField(blank=True, null=True, verbose_name='Texto da consulta')),
                ('historicoAtivo', models.BooleanField(default=True, verbose_name='Histórico ativo')),
                ('dataVerificacao', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='processos.processosmodel')),
            ],
        ),
    ]
