# Generated by Django 4.0.2 on 2022-05-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendenciasmodels',
            name='processo',
        ),
    ]
