# Generated by Django 4.0.2 on 2022-07-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_alter_historicoprocessosmodel_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisitosProcessosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do requisito')),
                ('descricao', models.TextField(verbose_name='Descrição do requisito')),
            ],
            options={
                'verbose_name': 'Requisito do processo',
                'verbose_name_plural': 'Requisitos do processos',
            },
        ),
    ]
