# Generated by Django 4.0.2 on 2022-07-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_requisitosprocessosmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelosProcessosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Modelo de Projeto')),
                ('sistemVinculado', models.CharField(choices=[('SIGMA', 'SIGMA - EB'), ('SINARM', 'SINARM - PF'), ('OUTROS', 'Outros..')], max_length=10, verbose_name='Sistema Vinculado')),
                ('requisitos', models.ManyToManyField(to='processos.requisitosProcessosModel')),
            ],
            options={
                'verbose_name': 'Modelo de processo',
                'verbose_name_plural': 'Modelo de processos',
            },
        ),
    ]
