# Generated by Django 4.0.2 on 2022-07-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_novosprocessosmodel_processosrequisitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novosprocessosmodel',
            name='dataRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
