# Generated by Django 4.0.2 on 2022-07-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_remove_processosrequisitos_dataalteracao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processosrequisitos',
            name='dataUltimaAlteracao',
        ),
    ]
