# Generated by Django 4.0.2 on 2022-08-28 22:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_novosprocessosmodel_dataprevistadeferimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelosprocessosmodel',
            options={'ordering': ['titulo', 'sistemVinculado'], 'verbose_name': 'Modelo de processo', 'verbose_name_plural': 'Modelo de processos'},
        ),
        migrations.AddField(
            model_name='novosprocessosmodel',
            name='nivelPrioridade',
            field=models.SmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Nível de prioridade'),
        ),
        migrations.CreateModel(
            name='anotacoesProcessosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacao', models.TextField(verbose_name='Anotação')),
                ('dataRegistro', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes_processos', to='processos.novosprocessosmodel')),
            ],
            options={
                'verbose_name': 'Anotação de processo',
                'verbose_name_plural': 'Anotações de processos',
            },
        ),
    ]
