# Generated by Django 4.0.2 on 2022-08-28 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0014_alter_modelosprocessosmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacoesprocessosmodel',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
    ]
