# Generated by Django 4.0.2 on 2022-03-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0004_alter_arquivosmodel_tipoarquivo'),
        ('clientes', '0004_alter_clientemodel_cpf'),
        ('enderecos', '0002_alter_enderecoclientemodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='declaracaoGuardaAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegistro', models.DateField(auto_now=True)),
                ('dataValidade', models.DateField(blank=True, null=True)),
                ('local', models.CharField(default='São Luís, MA', max_length=200, verbose_name='Local')),
                ('arquivo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.arquivosmodel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracaoGuardaAcervo', to='clientes.clientemodel')),
                ('enderecoClienteModel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enderecos.enderecoclientemodel')),
            ],
            options={
                'verbose_name': 'Declaração de guarda de acervo',
                'verbose_name_plural': 'Declarações de guarda de acervo',
            },
        ),
    ]
