# Generated by Django 4.0.2 on 2022-03-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('declaracoes', '0002_rename_enderecoclientemodel_declaracaoguardaacervo_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracaoguardaacervo',
            name='arquivo',
        ),
    ]
