# Generated by Django 4.0.2 on 2022-03-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_alter_enderecoclientemodel_table'),
        ('declaracoes', '0003_remove_declaracaoguardaacervo_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaoguardaacervo',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecos.enderecoclientemodel'),
        ),
    ]
