# Generated by Django 4.0.2 on 2022-03-27 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_clientemodel_nomemae_clientemodel_nomepai'),
        ('declaracoes', '0004_alter_declaracaoguardaacervo_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='declaracoesDiversas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('destinatario', models.CharField(max_length=200, verbose_name='Destinatário')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('local', models.CharField(default='São Luís, MA', max_length=200, verbose_name='Local')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracoesDiversas', to='clientes.clientemodel')),
            ],
            options={
                'verbose_name_plural': 'Declaração diversa',
            },
        ),
    ]
