# Generated by Django 4.0.2 on 2022-03-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracoes', '0006_alter_declaracoesdiversas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracoesdiversas',
            name='local',
            field=models.CharField(default='São Luís - MA', max_length=200, verbose_name='Local'),
        ),
    ]
