# Generated by Django 4.0.2 on 2022-03-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_clientemodel_nomemae_clientemodel_nomepai'),
        ('declaracoes', '0007_alter_declaracoesdiversas_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='declarcoesResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDeclarante', models.CharField(max_length=200, verbose_name='Nome do declarante')),
                ('rG', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Número do RG do declarante')),
                ('logradouro', models.CharField(blank=True, default='Sem informação', max_length=200, verbose_name='Logradouro')),
                ('estadoMunicipio', models.CharField(blank=True, default='Sem informação', max_length=60, verbose_name='Estado e município do endereço')),
                ('dataRegistro', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaracaoResidencia', to='clientes.clientemodel')),
            ],
        ),
    ]
