# Generated by Django 4.0.2 on 2022-03-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracoes', '0008_declarcoesresidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarcoesresidencia',
            name='cep',
            field=models.CharField(default=1, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declarcoesresidencia',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='Número do CPF do declarante'),
        ),
    ]
