# Generated by Django 4.0.2 on 2022-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracoes', '0009_declarcoesresidencia_cep_declarcoesresidencia_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarcoesresidencia',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='Número do CPF do declarante'),
        ),
    ]
