# Generated by Django 4.0.2 on 2022-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracoes', '0010_alter_declarcoesresidencia_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarcoesresidencia',
            name='rG',
            field=models.CharField(blank=True, max_length=40, verbose_name='Número do RG do declarante'),
        ),
    ]
