# Generated by Django 4.0.2 on 2022-03-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosfinanceiromodel',
            name='codigoBarra',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código de barras'),
        ),
    ]
