# Generated by Django 4.0.2 on 2022-02-14 00:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contratosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('servicoConcluido', models.BooleanField(default=False, verbose_name='Serviço concluído')),
                ('servicoAtivo', models.BooleanField(default=True, verbose_name='Serviço ativo')),
                ('dataContrato', models.DateField(auto_now=True)),
                ('dataConclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('dataRegistro', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.clientemodel', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='servicosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Serviço')),
                ('sistemaVinculado', models.CharField(choices=[('EB', 'Exército Brasileiro'), ('PF', 'Polícia Federal')], max_length=10)),
                ('ativo', models.BooleanField(default=True, verbose_name='Serviço disponível')),
            ],
        ),
        migrations.CreateModel(
            name='valorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True, verbose_name='Valor do serviço')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='notificacoeesContratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da notificação')),
                ('dataNotificacao', models.DateTimeField(auto_now=True)),
                ('entregue', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='servicos.contratosmodel', verbose_name='Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Item')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True, verbose_name='Valor do serviço')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='servicos.servicosmodel')),
            ],
        ),
        migrations.AddField(
            model_name='contratosmodel',
            name='servicos',
            field=models.ManyToManyField(to='servicos.servicosModel'),
        ),
    ]
