# Generated by Django 4.0.2 on 2022-02-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servicosmodel_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicosmodel',
            options={'ordering': ['nome', 'sistemaVinculado'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='itemservico',
            name='adicional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True, verbose_name='Valor adicional'),
        ),
        migrations.AddField(
            model_name='itemservico',
            name='observacao',
            field=models.TextField(blank=True, default='Sem observações'),
        ),
    ]
