# Generated by Django 4.0.2 on 2022-02-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_transferenciasigmasigma'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferenciasigmasigma',
            name='local',
            field=models.CharField(default='São Luís - MA', max_length=150),
        ),
    ]
