# Generated by Django 4.0.2 on 2022-02-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0008_remove_transferenciasigmasigma_itemservico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferenciasigmasigma',
            name='servico',
        ),
        migrations.AddField(
            model_name='transferenciasigmasigma',
            name='contrato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='servicos.contratosmodel'),
            preserve_default=False,
        ),
    ]
