# Generated by Django 4.0.2 on 2022-02-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0002_armasclientes_mudandapropriedade'),
        ('servicos', '0010_alter_transferenciasigmasigma_datadeferimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferenciasigmasigma',
            name='arma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='armas.armasclientes'),
        ),
    ]
