# Generated by Django 4.0.2 on 2022-02-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('servicos', '0012_emissaoguiatrafego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratosmodel',
            name='servicos',
        ),
        migrations.RemoveField(
            model_name='transferenciasigmasigma',
            name='contrato',
        ),
        migrations.AddField(
            model_name='contratosmodel',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contratosmodel',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
