# Generated by Django 4.0.2 on 2022-02-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0014_emissaoguiatrafego_municoeslote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissaoguiatrafego',
            name='municoes',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Espeficicações da munição'),
        ),
        migrations.AlterField(
            model_name='emissaoguiatrafego',
            name='municoesLote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote da munição'),
        ),
        migrations.AlterField(
            model_name='emissaoguiatrafego',
            name='municoesQuantidade',
            field=models.SmallIntegerField(default=0, verbose_name='Quantidadede de Munições'),
        ),
    ]
