# Generated by Django 4.0.2 on 2022-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0016_remove_itemservico_servico_delete_valoritem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='listaServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('vinculoSistema', models.CharField(choices=[('EB', 'Exército Brasileiro'), ('PF', 'Polícia Federal')], max_length=3)),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Link do sistema')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lista de serviços',
                'ordering': ['vinculoSistema', 'nome'],
            },
        ),
    ]
