# Generated by Django 4.0.2 on 2022-02-19 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientemodel_senhaacessogov'),
        ('servicos', '0018_alter_emissaoguiatrafego_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='armaseAcessorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('calibre', models.CharField(max_length=100, verbose_name='Calibre')),
                ('marcaModelo', models.CharField(max_length=100, verbose_name='Marca/Modelo')),
                ('quantidade', models.SmallIntegerField(default=1, verbose_name='Quantidade')),
            ],
        ),
        migrations.CreateModel(
            name='aquisicaoPCE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(choices=[('cacador', 'Caçador'), ('atirador', 'Atirador'), ('colecionador', 'Colecionador')], default='atirador', max_length=20, verbose_name='Finalidade da aquisição')),
                ('dadosTecnicos', models.CharField(blank=True, default='Sem informações', max_length=200, null=True, verbose_name='Dados técnicos esclarecedores do acessório')),
                ('fornecedor', models.CharField(max_length=50, verbose_name='Fornecedor')),
                ('cR', models.CharField(max_length=15, verbose_name='CR do fornecedor')),
                ('outrasInformacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Outras informações')),
                ('local', models.CharField(blank=True, default='São Luís - MA', max_length=100)),
                ('dataRegistro', models.DateField(auto_now=True)),
                ('armasAcessorios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquisicaoPCE', to='servicos.armaseacessorios')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquisicaoPCE', to='clientes.clientemodel')),
            ],
        ),
    ]
