# Generated by Django 4.0.2 on 2022-02-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0019_armaseacessorios_aquisicaopce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquisicaopce',
            name='armasAcessorios',
        ),
        migrations.AddField(
            model_name='aquisicaopce',
            name='armasAcessorios',
            field=models.ManyToManyField(related_name='aquisicaoPCE', to='servicos.armaseAcessorios'),
        ),
    ]
