# Generated by Django 4.0.2 on 2022-02-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0020_remove_aquisicaopce_armasacessorios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquisicaopce',
            name='armasAcessorios',
        ),
        migrations.AddField(
            model_name='armaseacessorios',
            name='processo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='armaseAcessorios', to='servicos.aquisicaopce'),
            preserve_default=False,
        ),
    ]
