# Generated by Django 4.0.2 on 2022-02-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0022_aquisicaopce_uuid_emissaoguiatrafego_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquisicaopce',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='emissaoguiatrafego',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='servicosmodel',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='transferenciasigmasigma',
            name='uuid',
        ),
    ]
