# Generated by Django 4.0.2 on 2022-02-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0023_remove_aquisicaopce_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratosmodel',
            name='codigo',
        ),
    ]
