# Generated by Django 4.0.2 on 2022-02-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0024_remove_contratosmodel_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquisicaopce',
            name='anexos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Anexos'),
        ),
    ]
