# Generated by Django 4.0.2 on 2022-02-20 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0025_aquisicaopce_anexos'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagamentosServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPagamento', models.DateField(default=datetime.datetime(2022, 2, 20, 19, 54, 4, 800446), verbose_name='Data do pagamento')),
                ('formaPagamento', models.CharField(default='Pix', max_length=100, verbose_name='Forma de pagamento')),
                ('valorPago', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Valor pago')),
            ],
        ),
        migrations.RemoveField(
            model_name='notificacoeescontratos',
            name='contrato',
        ),
        migrations.AlterField(
            model_name='servicosmodel',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Valor do serviço'),
        ),
        migrations.DeleteModel(
            name='contratosModel',
        ),
        migrations.DeleteModel(
            name='notificacoeesContratos',
        ),
        migrations.AddField(
            model_name='pagamentosservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='servicos.servicosmodel'),
        ),
    ]
