# Generated by Django 4.0.2 on 2022-02-20 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0027_pagamentosservico_confirmado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicosmodel',
            name='statusServico',
        ),
        migrations.CreateModel(
            name='movimentacoesServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusServico', models.CharField(choices=[('aguardandopagamento', 'Aguardando pagamentoo'), ('iniciado', 'Iniciado'), ('documentacao', 'Juntando documentação'), ('protocolado', 'Protoloado'), ('analise', 'Em análise pelo órgão'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido')], default='aguardandopagamento', max_length=30, verbose_name='Status do serviço')),
                ('dataMovimentacao', models.DateField(verbose_name='Data da movimentação')),
                ('dataRegistro', models.DateTimeField(auto_now=True)),
                ('movimentacaoAtiva', models.BooleanField(default=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='servicos.servicosmodel')),
            ],
            options={
                'ordering': ['servico', 'dataMovimentacao'],
            },
        ),
    ]
