# Generated by Django 4.0.2 on 2022-02-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0028_remove_servicosmodel_statusservico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaservicos',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='Valor do serviço'),
        ),
    ]
