# Generated by Django 4.0.2 on 2022-02-21 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientemodel_senhaacessogov'),
        ('servicos', '0029_listaservicos_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clube', models.CharField(default='CLAM', max_length=200, verbose_name='Clube a filiar')),
                ('dataRegistro', models.DateField(auto_now=True)),
                ('dataDeferimento', models.DateField(blank=True, null=True)),
                ('deferido', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registro_CR', to='clientes.clientemodel')),
            ],
        ),
    ]
