# Generated by Django 4.0.2 on 2022-02-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0030_registrocr'),
    ]

    operations = [
        migrations.CreateModel(
            name='exigenciasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da exigência')),
            ],
        ),
        migrations.AddField(
            model_name='listaservicos',
            name='exigencias',
            field=models.ManyToManyField(related_name='exigencias', to='servicos.exigenciasModel'),
        ),
    ]
