# Generated by Django 4.0.2 on 2022-02-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('servicos', '0032_alter_exigenciasmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cumprimentoExigenciasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cumprida', models.BooleanField(default=False)),
                ('dataRegistro', models.DateField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('exigencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumprimento_exigencias', to='servicos.exigenciasmodel')),
            ],
        ),
    ]
