# Generated by Django 4.0.2 on 2022-02-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0033_cumprimentoexigenciasmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrocr',
            name='exigencias',
        ),
        migrations.AddField(
            model_name='listaservicos',
            name='exigencias',
            field=models.ManyToManyField(related_name='exigencias', to='servicos.exigenciasModel'),
        ),
        migrations.AddField(
            model_name='servicosmodel',
            name='tipoServico',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_servico', to='servicos.listaservicos'),
            preserve_default=False,
        ),
    ]
