# Generated by Django 4.0.2 on 2022-02-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0034_remove_registrocr_exigencias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumprimentoexigenciasmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cumprimentoexigenciasmodel',
            name='object_id',
        ),
        migrations.AddField(
            model_name='cumprimentoexigenciasmodel',
            name='servico',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='cumprimento_exigencias_servico', to='servicos.servicosmodel'),
            preserve_default=False,
        ),
    ]
