# Generated by Django 4.0.2 on 2022-02-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0035_remove_cumprimentoexigenciasmodel_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigenciasmodel',
            name='ExtensaoArquivo',
            field=models.CharField(default='pdf', max_length=5, verbose_name='Extensão do arquivo'),
        ),
    ]
