# Generated by Django 4.0.2 on 2022-03-03 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientemodel_senhaacessogov'),
        ('servicos', '0036_exigenciasmodel_extensaoarquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='apostilamentosExercito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rM', models.CharField(default='8ª', max_length=5, verbose_name='Região Militar')),
                ('objeto', models.CharField(choices=[('concessao', 'Concessão de registro'), ('revalidacao', 'Revalidação de registro'), ('apostilamento', 'Apostilamento ao registro'), ('segundavia', '2ª via do registro'), ('cancelamento', 'Cancelamento de registro')], max_length=200, verbose_name='Objeto de apostilamento')),
                ('atividade', models.CharField(default='TIRO DESPORTIVO', max_length=20, verbose_name='Atividade')),
                ('apostilamento', models.CharField(max_length=200, verbose_name='Apostilamento')),
                ('outrasInformacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Outras informações')),
                ('dataRegistro', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostilamentos', to='clientes.clientemodel')),
            ],
        ),
    ]
