# Generated by Django 4.0.2 on 2022-03-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0037_apostilamentosexercito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicosmodel',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=13, null=True, verbose_name='Valor do serviço'),
        ),
    ]
