# Generated by Django 4.0.2 on 2022-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0038_alter_servicosmodel_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostilamentosexercito',
            name='atividade',
            field=models.CharField(choices=[('atirador', 'TIRO DESPORTIVO'), ('cacador', 'CAÇA'), ('colecionador', 'COLECIONAMENTO')], max_length=20, verbose_name='Atividade'),
        ),
        migrations.AlterField(
            model_name='apostilamentosexercito',
            name='objeto',
            field=models.CharField(choices=[('concessao', 'Concessão de registro'), ('revalidacao', 'Revalidação de registro'), ('apostilamento', 'Apostilamento ao registro'), ('segundavia', '2ª via do registro'), ('cancelamento', 'Cancelamento de registro'), ('outros', 'Outros')], max_length=200, verbose_name='Objeto de apostilamento'),
        ),
    ]
