# Generated by Django 4.0.2 on 2022-03-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0007_remove_armasclientes_mudandapropriedade_and_more'),
        ('clientes', '0007_clientemodel_escolaridade'),
        ('servicos', '0039_alter_apostilamentosexercito_atividade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicosSisgcorpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(choices=[('registroCR', 'Concessão de registro CR'), ('autorizacao', 'Autorização de Aquisição de PCE'), ('registroPCE', 'Apostilamento e Registro do PCE'), ('gtPCE', 'Emissão de Guia de Tráfego do PCE')], max_length=20, verbose_name='Objeto do serviço')),
                ('gru', models.CharField(max_length=60, verbose_name='Código de barrras GRU')),
                ('ativo', models.BooleanField(default=True)),
                ('dataInicio', models.DateField(verbose_name='Data de início do processo')),
                ('dataRegistro', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicosSisgCorp', to='clientes.clientemodel', verbose_name='servicos_sisgcorp')),
                ('pce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos_sisgcorp', to='armas.armasclientes')),
            ],
        ),
        migrations.CreateModel(
            name='andamentoServicosSisgCorpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusServico', models.CharField(choices=[('aguardandopagamento', 'Aguardando pagamentoo'), ('iniciado', 'Iniciado'), ('documentacao', 'Juntando documentação'), ('protocolado', 'Protoloado'), ('analise', 'Em análise pelo órgão'), ('deferido', 'Deferido'), ('indeferido', 'Indeferido')], max_length=20, verbose_name='Status atual do serviço')),
                ('ativo', models.BooleanField(default=True)),
                ('dataRegistro', models.DateField(auto_now=True)),
                ('referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamento', to='servicos.servicossisgcorpmodel')),
            ],
        ),
    ]
