# Generated by Django 4.0.2 on 2022-03-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_clientemodel_escolaridade'),
        ('servicos', '0040_servicossisgcorpmodel_andamentoservicossisgcorpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicosmodel',
            name='tipoServico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_servico', to='servicos.listaservicos'),
        ),
        migrations.AlterField(
            model_name='servicossisgcorpmodel',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_sisgcorp', to='clientes.clientemodel', verbose_name='Cliente'),
        ),
    ]
