# Generated by Django 4.0.2 on 2022-03-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0042_alter_servicossisgcorpmodel_objeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicossisgcorpmodel',
            options={'verbose_name': 'Serviço SISGCRP', 'verbose_name_plural': 'Serviços SISGCRP'},
        ),
    ]
