# Generated by Django 4.0.2 on 2022-03-31 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0045_transferenciasinarmsigma'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultaProcessoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataVerificacao', models.DateField(verbose_name='Data da verificação')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='servicos.servicosmodel')),
            ],
            options={
                'verbose_name': 'Consulta ao processo',
                'verbose_name_plural': 'Consultas ao processo',
            },
        ),
    ]
