# Generated by Django 4.0.2 on 2022-04-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0046_consultaprocessomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consultaProcessoModel',
        ),
    ]
