# Generated by Django 4.0.2 on 2022-05-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0009_armasclientes_paisfabricacao'),
        ('clientes', '0015_remove_clientemodel_processosemandamento'),
        ('servicos', '0048_alter_transferenciasigmasigma_adquirente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='requerimentosFisicosSinarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoRequerimento', models.CharField(choices=[('sinarmsigma', 'TRANSFERÊNCIA DO SINARM PARA O SIGMA'), ('sigmasinarm', 'TRANSFERÊNCIA DO SIGMA PARA O SINARM'), ('reimpressao', 'REIMPRESSÃO DE CRAF'), ('portefuncional', 'PORTE FUNCIONAL'), ('outros', 'OUTROS')], max_length=20, verbose_name='Tipo de requerimento')),
                ('especificacoes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especificações')),
                ('opcaoPorte', models.CharField(blank=True, choices=[('defesa', 'Defesa Pessoal'), ('seguranca', 'Segurança de Diginatários'), ('funcionar', 'Funcional'), ('cacacor', 'Caçador de subsisistência')], max_length=20, null=True, verbose_name='Tipo de requerimento')),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='armas.armasclientes')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientemodel')),
            ],
        ),
    ]
