# Generated by Django 4.0.2 on 2022-05-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0050_requerimentosfisicossinarm_dataregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimentosfisicossinarm',
            name='opcaoPorte',
            field=models.CharField(blank=True, choices=[('defesa', 'Defesa Pessoal'), ('seguranca', 'Segurança de Diginatários'), ('funcionar', 'Funcional'), ('cacacor', 'Caçador de subsisistência')], max_length=20, null=True, verbose_name='Opções de Porte'),
        ),
    ]
