# Generated by Django 4.0.2 on 2022-05-19 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0051_alter_requerimentosfisicossinarm_opcaoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimentosfisicossinarm',
            name='bairro',
            field=models.CharField(default=1, max_length=50, verbose_name='Distrito/Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimentosfisicossinarm',
            name='cep',
            field=models.CharField(default=1, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimentosfisicossinarm',
            name='cnpj',
            field=models.CharField(default=1, max_length=20, verbose_name='CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimentosfisicossinarm',
            name='empresa',
            field=models.CharField(default=1, max_length=200, verbose_name='Empresa/Órgão de trabalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimentosfisicossinarm',
            name='enderecoCcomercial',
            field=models.CharField(default=datetime.datetime(2022, 5, 19, 8, 37, 43, 8169), max_length=200, verbose_name='Endereço comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimentosfisicossinarm',
            name='municipio',
            field=models.CharField(default=1, max_length=70, verbose_name='Município'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimentosfisicossinarm',
            name='telefoneComercial',
            field=models.CharField(default=1, max_length=15, verbose_name='Telefone Comercial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimentosfisicossinarm',
            name='uf',
            field=models.CharField(default=1, max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requerimentosfisicossinarm',
            name='tipoRequerimento',
            field=models.CharField(choices=[('sinarmsigma', 'TRANSFERÊNCIA DO SINARM PARA O SIGMA'), ('sigmasinarm', 'TRANSFERÊNCIA DO SIGMA PARA O SINARM'), ('reimpressao', 'REIMPRESSÃO DE CRAF'), ('portefuncional', 'PORTE FUNCIONAL'), ('outros', 'OUTROS')], max_length=20, verbose_name='Objetivo do requerimento'),
        ),
    ]
