# Generated by Django 4.0.2 on 2022-05-21 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0052_requerimentosfisicossinarm_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostilamentosexercito',
            name='atividade',
            field=models.CharField(choices=[('atirador', 'TIRO DESPORTIVO'), ('cacador', 'CAÇA'), ('colecionador', 'COLECIONAMENTO'), ('aquisicaoAcessorios', 'AQUISIÇÃO DE ACESSÓRIOS DE ARMA DE FOGO PARA TIRO DESPORTIVO/ ENDTIDADE DE TIRO DESPORTIVO / CAÇA')], max_length=20, verbose_name='Atividade'),
        ),
        migrations.CreateModel(
            name='itensRequerimentoApostilamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('marcaModelo', models.CharField(max_length=100, verbose_name='Marca/Modelo')),
                ('quantidade', models.SmallIntegerField(default=1, verbose_name='Quantidade')),
                ('fornecedor', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('crfornecedor', models.CharField(max_length=20, verbose_name='CR do Fornecedor')),
                ('notaFiscalData', models.CharField(max_length=30, verbose_name='Nota fiscal | data')),
                ('atorizacaoData', models.CharField(max_length=30, verbose_name='Autorização | data')),
                ('anexos', models.TextField(verbose_name='Anexos')),
                ('apostilamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='servicos.apostilamentosexercito')),
            ],
            options={
                'verbose_name': 'Item de requerimento de apostilamento',
                'verbose_name_plural': 'Itens de requerimento de apostilamento',
            },
        ),
    ]
