# Generated by Django 4.0.2 on 2022-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0053_alter_apostilamentosexercito_atividade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensrequerimentoapostilamento',
            name='anexos',
        ),
        migrations.AddField(
            model_name='apostilamentosexercito',
            name='anexos',
            field=models.TextField(default=1, verbose_name='Anexos'),
            preserve_default=False,
        ),
    ]
