# Generated by Django 4.0.2 on 2022-05-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0054_remove_itensrequerimentoapostilamento_anexos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostilamentosexercito',
            name='apostilamento',
            field=models.TextField(verbose_name='Apostilamento'),
        ),
        migrations.AlterField(
            model_name='apostilamentosexercito',
            name='outrasInformacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Outras informações'),
        ),
    ]
