# Generated by Django 4.0.2 on 2022-05-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0055_alter_apostilamentosexercito_apostilamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostilamentosexercito',
            name='apostilamento',
            field=models.CharField(max_length=200, verbose_name='Apostilamento'),
        ),
    ]
