# Generated by Django 4.0.2 on 2022-06-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_remove_historicoconsultasprocessosmodel_consulta_and_more'),
        ('armas', '0012_alter_armasclientes_orgaoexpedidor'),
        ('enderecos', '0002_alter_enderecoclientemodel_table'),
        ('servicos', '0056_alter_apostilamentosexercito_apostilamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='renovacaoCRAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localRequerimento', models.CharField(blank=True, default='São Luís - MA', max_length=200, verbose_name='Local de solicitação')),
                ('dataRegistro', models.DateTimeField(auto_now=True)),
                ('armas', models.ManyToManyField(related_name='armas', to='armas.armasClientes')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientemodel')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enderecos.enderecoclientemodel')),
            ],
            options={
                'verbose_name': 'Requerimento renovação CRAF/SIGMA',
                'verbose_name_plural': 'Requerimentos renovações CRAF/SIGMA',
            },
        ),
    ]
