# Generated by Django 4.0.2 on 2022-06-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0012_alter_armasclientes_orgaoexpedidor'),
        ('servicos', '0057_renovacaocraf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovacaocraf',
            name='armas',
            field=models.ManyToManyField(related_name='armas_renovacao_CRAF', to='armas.armasClientes'),
        ),
    ]
