# Generated by Django 4.0.2 on 2022-06-15 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0012_alter_armasclientes_orgaoexpedidor'),
        ('servicos', '0058_alter_renovacaocraf_armas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renovacaocraf',
            name='armas',
        ),
        migrations.AddField(
            model_name='renovacaocraf',
            name='arma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='renovacaoCRAFSIGMA', to='armas.armasclientes'),
            preserve_default=False,
        ),
    ]
