# Generated by Django 4.0.2 on 2022-06-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_clientecurso'),
        ('servicos', '0059_remove_renovacaocraf_armas_renovacaocraf_arma'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='clientesCursosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Código da matrícula')),
                ('matriculado', models.BooleanField(default=False)),
                ('dataRegistro', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.clientecurso')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicos.cursosmodel')),
            ],
            options={
                'verbose_name': 'Cliente por curso',
                'verbose_name_plural': 'Clientes por cursos',
            },
        ),
    ]
