# Generated by Django 4.0.2 on 2022-06-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0060_cursosmodel_clientescursosmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientescursosmodel',
            options={'ordering': ['dataRegistro', 'cliente'], 'verbose_name': 'Cliente por curso', 'verbose_name_plural': 'Clientes por cursos'},
        ),
        migrations.AlterField(
            model_name='clientescursosmodel',
            name='codigo',
            field=models.CharField(auto_created=b'&[\xab\xd3\xce\xb1', max_length=15, unique=True, verbose_name='Código da matrícula'),
        ),
    ]
