# Generated by Django 4.0.2 on 2022-07-15 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_clientecurso'),
        ('armas', '0012_alter_armasclientes_orgaoexpedidor'),
        ('servicos', '0061_alter_clientescursosmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientescursosmodel',
            name='codigo',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Código da matrícula'),
        ),
        migrations.CreateModel(
            name='termoDoacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localRequerimento', models.CharField(blank=True, default='São Luís - MA', max_length=200, verbose_name='Local de solicitação')),
                ('dataRegistro', models.DateTimeField(auto_now=True)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termoDoacao', to='armas.armasclientes')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doadorTermoDoacao', to='clientes.clientemodel', verbose_name='Doador')),
                ('donatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donatarioTermoDoacao', to='clientes.clientemodel', verbose_name='Donatário')),
            ],
            options={
                'verbose_name': 'Termo de doação',
                'verbose_name_plural': 'Termos de Doação',
                'ordering': ['dataRegistro', 'doador', 'donatario'],
            },
        ),
    ]
