# Generated by Django 4.0.2 on 2022-02-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_clientemodel_options_alter_clientemodel_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='armasClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('calibre', models.CharField(max_length=100)),
                ('sistemaVinculado', models.CharField(choices=[('SIGMA', 'SIGMA'), ('SINARM', 'SINARM')], max_length=100)),
                ('numeroSerie', models.CharField(max_length=100)),
                ('numeroSistema', models.CharField(max_length=100)),
                ('especificacoes', models.CharField(default='06 raias à direita', max_length=100)),
                ('acessorios', models.CharField(default='Não possui', max_length=100)),
                ('acabamento', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='armas', to='clientes.clientemodel')),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
            },
        ),
    ]
