# Generated by Django 4.0.2 on 2022-02-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armasclientes',
            name='mudandaPropriedade',
            field=models.BooleanField(default=False),
        ),
    ]
