# Generated by Django 4.0.2 on 2022-03-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0003_armasclientes_funcionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='armasclientes',
            name='capacidadeCarregador',
            field=models.SmallIntegerField(default=15, verbose_name='Capacidade do carregador'),
        ),
        migrations.AddField(
            model_name='armasclientes',
            name='raias',
            field=models.SmallIntegerField(default=6, verbose_name='Número de raias'),
        ),
        migrations.AddField(
            model_name='armasclientes',
            name='sentidoRaias',
            field=models.CharField(default='A direita', max_length=20, verbose_name='Sentido das raias'),
        ),
        migrations.AddField(
            model_name='armasclientes',
            name='tamanhoCano',
            field=models.SmallIntegerField(default=80, verbose_name='Tamanho em milímetro'),
        ),
    ]
