# Generated by Django 4.0.2 on 2022-03-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0004_armasclientes_capacidadecarregador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armasclientes',
            name='numeroCanos',
            field=models.SmallIntegerField(default=1, verbose_name='Número de canos'),
        ),
    ]
