# Generated by Django 4.0.2 on 2022-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0005_armasclientes_numerocanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='armasclientes',
            name='almaCano',
            field=models.CharField(default='Raidada', max_length=20, verbose_name='Alma do cano'),
        ),
    ]
