# Generated by Django 4.0.2 on 2022-03-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0006_armasclientes_almacano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armasclientes',
            name='mudandaPropriedade',
        ),
        migrations.AddField(
            model_name='armasclientes',
            name='mudancaPropriedade',
            field=models.BooleanField(default=False, verbose_name='Em processo de mudança de propriedade'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='acabamento',
            field=models.CharField(max_length=100, verbose_name='Acabamento'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='acessorios',
            field=models.CharField(default='Não possui', max_length=100, verbose_name='Acessórios'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='calibre',
            field=models.CharField(max_length=100, verbose_name='Calibre'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='especificacoes',
            field=models.CharField(default='06 raias à direita', max_length=100, verbose_name='Especificações'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='numeroSerie',
            field=models.CharField(max_length=100, verbose_name='Número de série'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='numeroSistema',
            field=models.CharField(max_length=100, verbose_name='Número de registro no sistema'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='sistemaVinculado',
            field=models.CharField(choices=[('SIGMA', 'SIGMA'), ('SINARM', 'SINARM')], max_length=100, verbose_name='Sistema vinculado'),
        ),
        migrations.AlterField(
            model_name='armasclientes',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
    ]
