# Generated by Django 4.0.2 on 2022-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0007_remove_armasclientes_mudandapropriedade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armasclientes',
            name='tamanhoCano',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=13, verbose_name='Tamanho em milímetro'),
        ),
    ]
