# Generated by Django 4.0.2 on 2022-05-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0008_alter_armasclientes_tamanhocano'),
    ]

    operations = [
        migrations.AddField(
            model_name='armasclientes',
            name='paisFabricacao',
            field=models.CharField(default='Brasil', max_length=30, verbose_name='País de fabricação'),
        ),
    ]
