# Generated by Django 4.0.2 on 2022-05-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armas', '0010_armasclientes_numeroregistro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armasclientes',
            name='dataRegistro',
            field=models.DateField(blank=True, null=True, verbose_name='Data do registro'),
        ),
    ]
