# Generated by Django 4.0.2 on 2022-03-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientemodel_senhaacessogov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Número do CPF'),
        ),
    ]
