# Generated by Django 4.0.2 on 2022-03-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_clientemodel_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='Número do CPF'),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='tituloEleitor',
            field=models.CharField(blank=True, default='Sem informação', max_length=15, verbose_name='Título de eleitor'),
        ),
    ]
