# Generated by Django 4.0.2 on 2022-03-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_clientemodel_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientemodel',
            options={'ordering': ['nome', '-dataRegistro'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
