# Generated by Django 4.0.2 on 2022-03-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_clientemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='escolaridade',
            field=models.CharField(default='medio', max_length=10, verbose_name='Escolaridade'),
        ),
    ]
