# Generated by Django 4.0.2 on 2022-03-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_clientemodel_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='escolaridade',
            field=models.CharField(choices=[('fundamental', 'Fundamental Completo'), ('medio', 'Médio Completo'), ('superior', 'Superior Completo')], default='medio', max_length=15, verbose_name='Escolaridade'),
        ),
    ]
