# Generated by Django 4.0.2 on 2022-03-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_clientemodel_escolaridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='nomeMae',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AddField(
            model_name='clientemodel',
            name='nomePai',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Pai'),
        ),
    ]
