# Generated by Django 4.0.2 on 2022-04-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_clientemodel_nomemae_clientemodel_nomepai'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='processosEmAndamento',
            field=models.BooleanField(default=True, verbose_name='Cliente com processo em andamento'),
        ),
        migrations.CreateModel(
            name='consultaProcessosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(max_length=200, verbose_name='Identificaçaõ do processo')),
                ('descricao', models.TextField(verbose_name='Descrição da consulta')),
                ('dataVerificacao', models.DateField(verbose_name='Data da verificação')),
                ('consultaAtiva', models.BooleanField(blank=True, verbose_name='Consulta Ativa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='clientes.clientemodel')),
            ],
            options={
                'verbose_name': 'Consulta ao processo',
                'verbose_name_plural': 'Consultas a processos',
                'ordering': ['dataVerificacao', 'cliente'],
            },
        ),
    ]
