# Generated by Django 4.0.2 on 2022-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_clientemodel_processosemandamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaprocessosmodel',
            name='consultaAtiva',
            field=models.BooleanField(default=True, verbose_name='Consulta Ativa'),
        ),
    ]
