# Generated by Django 4.0.2 on 2022-04-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_consultaprocessosmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaprocessosmodel',
            name='dataVerificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da última verificação'),
        ),
        migrations.AlterField(
            model_name='historicoconsultasprocessosmodel',
            name='textoConsulta',
            field=models.TextField(blank=True, null=True, verbose_name='Texto da consulta'),
        ),
    ]
