# Generated by Django 4.0.2 on 2022-04-23 17:44

import clientes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_consultaprocessosmodel_dataverificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='fotoPerfil',
            field=models.ImageField(blank=True, default='fotos_clientes/semAvatar.png', null=True, upload_to=clientes.models.local_avatarCliente, verbose_name='Foto do Perfil'),
        ),
    ]
