# Generated by Django 4.0.2 on 2022-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_remove_historicoconsultasprocessosmodel_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='estadoCivil',
            field=models.CharField(choices=[('C', 'Casado'), ('D', 'Divorciado'), ('S', 'Solteiro'), ('U', 'União estável'), ('V', 'Viúvo')], default='S', max_length=1, verbose_name='Estado civil'),
        ),
    ]
