# Generated by Django 4.0.2 on 2022-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_clientecurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Cliente com processo em andamento'),
        ),
    ]
