# Generated by Django 4.0.2 on 2022-08-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_clientemodel_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='Cliente sem Pendências'),
        ),
    ]
