# Generated by Django 4.0.2 on 2022-12-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_alter_clientemodel_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='escolaridade',
            field=models.CharField(choices=[('FUNDAMENTAL', 'Fundamental Completo'), ('MEDIO', 'Médio Completo'), ('SUPERIOR', 'Superior Completo')], default='medio', max_length=15, verbose_name='Escolaridade'),
        ),
    ]
