# Generated by Django 4.0.2 on 2022-02-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enderecoClienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=True)),
                ('logradouro', models.CharField(blank=True, default='Sem informação', max_length=200, verbose_name='Logradouro')),
                ('estadoMunicipio', models.CharField(blank=True, default='Sem informação', max_length=60, verbose_name='Estado e município do endereço')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enderecos_cliente', to='clientes.clientemodel')),
            ],
            options={
                'verbose_name': 'Endereço do cliente',
                'verbose_name_plural': 'Endereços de clientes',
            },
        ),
    ]
