# Generated by Django 4.0.2 on 2022-02-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enderecoclientemodel',
            table='clientes_enderecoclientemodel',
        ),
    ]
