# Generated by Django 4.0.2 on 2022-03-09 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0007_clientemodel_escolaridade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pendenciasModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da pendência')),
                ('textoPendencia', models.TextField(blank=True, null=True, verbose_name='Detalhamento da pendência pendência')),
                ('statusPendencia', models.BooleanField(default=True, verbose_name='Pendente')),
                ('dataRegistro', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='clientes.clientemodel')),
                ('usuario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendendias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendência',
                'verbose_name_plural': 'Pendências',
                'ordering': ['dataRegistro'],
            },
        ),
    ]
