# Generated by Django 4.0.2 on 2022-03-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendenciasmodels',
            name='escalaPrioridade',
            field=models.SmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2, verbose_name='Escala de prioridade'),
        ),
    ]
