# Generated by Django 4.0.2 on 2022-03-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_pendenciasmodels_escalaprioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasmodels',
            name='textoPendencia',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhamento da pendência'),
        ),
    ]
