# Generated by Django 4.0.2 on 2022-03-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_alter_pendenciasmodels_textopendencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendenciasmodels',
            name='dataConclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
