# Generated by Django 4.0.2 on 2022-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_pendenciasmodels_dataconclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasmodels',
            name='dataConclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da conclusão'),
        ),
        migrations.AlterField(
            model_name='pendenciasmodels',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Identificação da pendência'),
        ),
        migrations.AlterField(
            model_name='pendenciasmodels',
            name='statusPendencia',
            field=models.BooleanField(default=True, verbose_name='Realizado'),
        ),
    ]
