# Generated by Django 4.0.2 on 2022-05-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_alter_pendenciasmodels_statuspendencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendenciasmodels',
            options={'ordering': ['escalaPrioridade', 'dataRegistro'], 'verbose_name': 'Pendência', 'verbose_name_plural': 'Pendências'},
        ),
        migrations.AddField(
            model_name='pendenciasmodels',
            name='dataLimite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Limite ou Vencimento'),
        ),
    ]
