# Generated by Django 4.0.2 on 2022-05-18 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0007_alter_pendenciasmodels_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendenciasmodels',
            name='usuario',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pendendias', to=settings.AUTH_USER_MODEL),
        ),
    ]
