# Generated by Django 4.0.2 on 2022-05-26 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_alter_pendenciasmodels_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pendenciasModels',
        ),
    ]
