# Generated by Django 4.0.2 on 2022-05-30 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestao', '0009_delete_pendenciasmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfilUsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(default='Colaborador', max_length=20)),
                ('avatar', models.ImageField(upload_to='', verbose_name='Imagem do perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
