# Generated by Django 4.0.2 on 2022-05-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuariomodel',
            options={'verbose_name': 'Perfil de usuário', 'verbose_name_plural': 'Perfis de usuários'},
        ),
        migrations.AlterField(
            model_name='perfilusuariomodel',
            name='avatar',
            field=models.ImageField(upload_to='usuarios', verbose_name='Imagem do perfil'),
        ),
    ]
