# Generated by Django 4.0.2 on 2022-08-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_alter_perfilusuariomodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuariomodel',
            name='nivelAcesso',
            field=models.SmallIntegerField(default=1, verbose_name='Nível de acesso'),
        ),
    ]
